/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#ffb4ab',
        'on-primary-fixed-variant': '#900c18',
        'outline-variant': '#e1bebc',
        'surface-dim': '#fcdbd8',
        'on-tertiary-container': '#d1d0d0',
        'tertiary-fixed': '#e4e2e2',
        'on-secondary-container': '#636262',
        tertiary: '#414242',
        'on-primary-container': '#ffc2bd',
        'surface-tint': '#b2292c',
        'surface-container-highest': '#e1e3e4',
        'on-surface-variant': '#59413f',
        'secondary-container': '#e2dfde',
        'surface-container-high': '#e7e8e9',
        primary: '#890414',
        surface: '#f8f9fa',
        'on-tertiary-fixed': '#1b1c1c',
        error: '#ba1a1a',
        'on-background': '#191c1d',
        'surface-variant': '#e1e3e4',
        outline: '#8d706e',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#410004',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#ffb3ae',
        'on-secondary-fixed': '#1c1b1b',
        'primary-container': '#ab2428',
        'on-tertiary': '#ffffff',
        background: '#f8f9fa',
        'on-error-container': '#93000a',
        'secondary-fixed': '#e5e2e1',
        'tertiary-container': '#595959',
        'on-secondary-fixed-variant': '#474746',
        'surface-container': '#edeeef',
        'tertiary-fixed-dim': '#c7c6c6',
        secondary: '#5f5e5e',
        'surface-container-low': '#f3f4f5',
        'inverse-on-surface': '#f0f1f2',
        'on-tertiary-fixed-variant': '#464747',
        'on-error': '#ffffff',
        'surface-bright': '#f8f9fa',
        'on-primary': '#ffffff',
        'primary-fixed': '#ffdad7',
        'on-secondary': '#ffffff',
        'inverse-surface': '#2e3132',
        'on-surface': '#191c1d',
        'secondary-fixed-dim': '#c8c6c5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'touch-target-min': '48px',
        'container-margin-mobile': '16px',
        'container-margin-desktop': '32px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Hanken Grotesk', 'sans-serif'],
        'title-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Hanken Grotesk', 'sans-serif'],
        'label-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-sm': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
};
